Refactor expiring thread code
JustAnyones/Pidroid pull request #24
Opened 2022-05-15 17:49 UTC by erksmit

Moves code related to expiring threads out of the plugin store cog. Instead using a seperate cog, so that any cog can use them.

2022-05-16 15:42 UTC, JustAnyones requested changes

2022-05-16 15:42 UTC, JustAnyones commented on bot/cogs/utils/api.py
>          return self.db["Plugin_threads"]
Collection string should be changed

2022-05-16 15:42 UTC, JustAnyones commented on bot/cogs/utils/api.py
> +        await self.create_new_expiring_thread(thread.id, expire_timestamp)
I would rather have this defined in the Pidroid object

2022-05-20 23:03 UTC, JustAnyones requested changes

2022-05-20 23:03 UTC, JustAnyones commented on bot/client.py
> +    async def create_expiring_thread(self, message: Message, name: str, expire_timestamp: int):
Add support for specifying custom auto archive duration

2022-06-02 18:01 UTC, JustAnyones requested changes
auto_archive_duration parameter is not type-hinted

2022-06-02 18:04 UTC, erksmit commented
My pr is in shambles

2022-06-06 12:15 UTC, JustAnyones commented
Looks good, resolve the conflict and it will be merged.

2022-06-06 22:35 UTC, JustAnyones approved these changes

2022-06-06 22:35 UTC, merged